name: R-uber tests

on:
    push:
        branches: [ "dev" ]
    pull_request:
        branches: [ "dev" ]

env:
    CARGO_TERM_COLOR: always

permissions:
    contents: write
    id-token: write
    actions: write

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            # Checkout
            - name: Checkout
              uses: actions/checkout@v4

            # Cache
            - name: Install toolchain
              run: rustup toolchain install stable --profile minimal

            - name: Cache
              uses: Swatinem/rust-cache@v2
              with:
                  save-if: ${{ github.ref == 'refs/heads/dev' }}

            # Build and test
            - name: Build
              run: cargo build --verbose

            - name: Run tests
              run: cargo test --verbose

            # Clippy
            - name: Add Clippy
              run: rustup component add clippy

            - name: Run Clippy
              uses: actions-rs/clippy-check@v1
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  args: --all-features

            # Audit
            - name: Audit checkout
              uses: actions/checkout@v4

            - name: Audit check
              uses: actions-rs/audit-check@v1
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
