name: R-uber tests

on:
    push:
        branches: [ "dev" ]
    pull_request:
        branches: [ "dev" ]

env:
    CARGO_TERM_COLOR: always

permissions:
    contents: write
    id-token: write
    actions: write

jobs:
    build_all:
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            - uses: actions/checkout@v4

            # Cache
            - run: rustup toolchain install stable --profile minimal
            - uses: Swatinem/rust-cache@v2
              with:
                  save-if: ${{ github.ref == 'refs/heads/dev' }}

            # Build and test
            - name: Build
              run: cargo build --verbose
            - name: Run tests
              run: cargo test --verbose

            # Clippy
            -   run: rustup component add clippy
            -   uses: actions-rs/clippy-check@v1
                with:
                    token: ${{ secrets.GITHUB_TOKEN }}
                    args: --all-features

            # Audit
            -   uses: actions/checkout@v4
            -   uses: actions-rs/audit-check@v1
                with:
                    token: ${{ secrets.GITHUB_TOKEN }}

#    clippy:
#        runs-on: ubuntu-latest
#        permissions:
#            contents: read
#        steps:
#            - uses: actions/checkout@v4
#            - run: rustup component add clippy
#            - uses: actions-rs/clippy-check@v1
#              with:
#                  token: ${{ secrets.GITHUB_TOKEN }}
#                  args: --all-features

#    audit:
#        runs-on: ubuntu-latest
#        steps:
#            - uses: actions/checkout@v4
#            - uses: actions-rs/audit-check@v1
#              with:
#                  token: ${{ secrets.GITHUB_TOKEN }}

#    build:
#        runs-on: ubuntu-latest
#        steps:
#            - uses: actions/checkout@v4
#            - name: Build
#              run: cargo build --verbose
#            - name: Run tests
#              run: cargo test --verbose
